/* Workout App service worker — offline-first app shell cache.
 * Generated by make-sw.py; do not hand-edit (version 20260910-1757). */
const SW_VERSION = "20260910-1757";
const CACHE_NAME = "workout-app-" + SW_VERSION;
const ASSETS = [
    "./",
    "index.html",
    "manifest.webmanifest",
    "icon-180.png",
    "icon-512.png",
    "assets/styles.css",
    "data/exercises-db.js",
    "assets/js/app-bootstrap.js",
    "assets/js/catalog.js",
    "assets/js/custom-exercises.js",
    "assets/js/dashboard-stats.js",
    "assets/js/exercise-detail.js",
    "assets/js/exercise-library.js",
    "assets/js/navigation.js",
    "assets/js/persistence.js",
    "assets/js/program-templates.js",
    "assets/js/programs.js",
    "assets/js/progression.js",
    "assets/js/sample-data.js",
    "assets/js/set-tags.js",
    "assets/js/state.js",
    "assets/js/supersets.js",
    "assets/js/utilities.js",
    "assets/js/workout-builder.js",
    "assets/js/workout-editor.js",
    "assets/js/workout-history.js"
];

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => cache.addAll(ASSETS)).then(() => self.skipWaiting())
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) =>
        Promise.all(
          keys
            .filter((k) => k.startsWith("workout-app-") && k !== CACHE_NAME)
            .map((k) => caches.delete(k))
        )
      )
      .then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", (event) => {
  if (event.request.method !== "GET") return;
  const url = new URL(event.request.url);
  if (url.origin !== self.location.origin) return;
  event.respondWith(
    caches.match(event.request).then(
      (hit) =>
        hit ||
        fetch(event.request)
          .then((res) => {
            if (res.ok) {
              const copy = res.clone();
              caches.open(CACHE_NAME).then((cache) => cache.put(event.request, copy));
            }
            return res;
          })
          .catch(() => caches.match("index.html"))
    )
  );
});
